var _contributors = [
    { name: "Sara Arjona", company: "Moodle" },
    { name: "Jeff Bohrer", company: "IMS Global" },
    { name: "Timothy F. Cook", company: "LRNG" },
    { name: "Maria Esquela", company: "eNABLE Community" },
    { name: "Steve Gance", company: "Washington State Board for Community and Technical Colleges" },
    { name: "Jim Goodell", company: "QIP/CEDS" },
    { name: "Markus Gylling", company: "IMS Global" },
    { name: "Viktor Haag", company: "D2L" },
    { name: "Takahiro Hata", company: "Digital Knowledge EdTech Lab" },
    { name: "Alexander Hripak", company: "Credly", role: "Editor" },
    { name: "Chris Houston", company: "eLumen" },
    { name: "Kerrie Lemoie", company: "OpenWorks Group" },
    { name: "Mark Leuba", company: "IMS Global" },
    { name: "Randy Macdonald", company: "Innovation Academy / InnovateOregon" },
    { name: "Andy Miller", company: "IMS Global" },
    { name: "Omid Mufeed", company: "Digitalme" },
    { name: "Nate Otto", company: "Concentric Sky" },
    { name: "Justin Pitcher", company: "Campus Labs" },
    { name: "Serge Ravet", company: "ADPIOS, BadgeEU" },
    { name: "Alex Reis", company: "D2L" },
    { name: "Jarin Schmidt", company: "Pearson Acclaim" },
    { name: "Attila Szabo-Nagy", company: "Erasmus+" }
];