var _contributors = [
  {name: "Nate Otto", company: "Concentric Sky, Skybridge Skills", companyURL: "", role: "Invited Expert"},
  {name: "Kerri Lemoie", company: "Concentric Sky, RANDA", companyURL: "", role: "Editor"},
  {name: "Phillip Long", company: "Concentric Sky", companyURL: "", role: "Invited Expert"},
  {name: "Marty Reed", company: "RANDA Solutions", companyURL: "", role: "Co-chair, CLR"},
  {name: "Justin Pitcher", company: "Anthology", companyURL: "", role: "Co-chair, OB"},
  {name: "Brent Cappriotti", company: "RANDA Solutions", companyURL: "", role: "Co-chair, CLR"},
  {name: "Sherri Braxton", company: "Bowdoin College", companyURL: "", role: "Co-chair, OB"},
  {name: "Jock Wright", company: "VerifyEd", companyURL: "", role: ""},
  {name: "Jen Schreiber", company: "Workday", companyURL: "", role: ""},
  {name: "Viktor Haag", company: "D2L", companyURL: "", role: ""},
  {name: "Alex Hripak", company: "Credly", companyURL: "", role: ""},
  {name: "David Ward", company: "PCG", companyURL: "", role: ""},
  {name: "Laura Janusek", company: "D2L", companyURL: "", role: ""},
  {name: "John Kuo", company: "Arizona State University", companyURL: "", role: ""},
  {name: "Sara Arjona", company: "Moodle HQ", companyURL: "", role: ""},
  {name: "Mark McConahay", company: "AACRAO", companyURL: "", role: "Invited Expert"},
  {name: "Dmitri Zagidulin", company: "DCC", companyURL: "", role: "Invited Expert"},
  {name: "Tracy Korsmo", company: "North Dakota IT (NDIT)", companyURL: "", role: ""},
  {name: "Kate Giovacchini", company: "Arizona State University", companyURL: "", role: ""},
  {name: "Andy Miller", company: "1Edtech", companyURL: "", role: "Editor"},
  {name: "Markus Gylling", company: "1Edtech", companyURL: "", role: "Editor"},
  {name: "Dan Blickensderfer", company: "1Edtech", companyURL: "", role: "Editor"}
];
