var _iprs = [
    { specVersion: "3.0", company: "Concentric Sky", electionDate: "October 24, 2019", necessaryClaims: "No", type: "RF RAND (Required & Optional Elements)" },
    { specVersion: "3.0", company: "Arizona State University", electionDate: "June 21, 2022", necessaryClaims: "No", type: "RF RAND (Required & Optional Elements)" },
    { specVersion: "3.0", company: "Temple University", electionDate: "June 10, 2022", necessaryClaims: "No", type: "RF RAND (Required & Optional Elements)" },
    { specVersion: "3.0", company: "Credly", electionDate: "October 3, 2019", necessaryClaims: "No", type: "RF RAND (Required & Optional Elements)" },
    { specVersion: "3.0", company: "Workday, Inc.", electionDate: "June 10, 2022", necessaryClaims: "No", type: "RF RAND (Required & Optional Elements)" },
    { specVersion: "3.0", company: "RANDA Solutions", electionDate: "June 9, 2022", necessaryClaims: "No", type: "RF RAND (Required & Optional Elements)" },
    { specVersion: "3.0", company: "Anthology", electionDate: "April 16, 2024", necessaryClaims: "No", type: "RF RAND (Required & Optional Elements)" },
    { specVersion: "3.0", company: "Unicon", electionDate: "April 22, 2024", necessaryClaims: "No", type: "RF RAND (Required & Optional Elements)" },
    { specVersion: "3.0", company: "Bowdoin College", electionDate: "June 11, 2022", necessaryClaims: "No", type: "RF RAND (Required & Optional Elements)" },
    { specVersion: "3.0", company: "American Association of Collegiate Registrars and Admissions Officers (AACARO)", electionDate: "April 15, 2024", necessaryClaims: "No", type: "RF RAND (Required & Optional Elements)" },
    { specVersion: "3.0", company: "Desire to Learn (D2L)", electionDate: "April 16, 2024", necessaryClaims: "No", type: "RF RAND (Required & Optional Elements)" } ,
    { specVersion: "3.0", company: "Digital Knowledge EdTech Lab Inc.", electionDate: "April 24, 2024", necessaryClaims: "No", type: "RF RAND (Required & Optional Elements)" },
    { specVersion: "3.0", company: "IQC Italian Quality Company", electionDate: "April 19, 2024", necessaryClaims: "No", type: "RF RAND (Required & Optional Elements)" },
    { specVersion: "3.0", company: "Skybridge Skills", electionDate: "April 16, 2024", necessaryClaims: "No", type: "RF RAND (Required & Optional Elements)" },
    { specVersion: "3.0", company: "Navigatr", electionDate: "April 25, 2024", necessaryClaims: "No", type: "RF RAND (Required & Optional Elements)" },
    { specVersion: "3.0", company: "T3 Innovation Network, US Chamber of Commerce Foundation", electionDate: "April 25, 2024", necessaryClaims: "No", type: "RF RAND (Required & Optional Elements)" },
    { specVersion: "3.0", company: "Territorium", electionDate: "April 23, 2024", necessaryClaims: "No", type: "RF RAND (Required & Optional Elements)" },
    { specVersion: "3.0", company: "Western Governors University (WGU) ", electionDate: "June 11, 2022", necessaryClaims: "No", type: "RF RAND (Required & Optional Elements)" }
];
