openapi: '3.0.0'

#####################################################################################
#                               API Information                                     #
#####################################################################################
info: 
    version: '2.1'
    title: Open Badges OpenAPI (YAML) Definition
    description: @@@TBD
    termsOfService: Permission is granted to all parties to use excerpts from this document as needed in producing requests for proposals. The limited permissions granted above are perpetual and will not be revoked by IMS or its successors or assigns. THIS API DEFINITION IS BEING OFFERED WITHOUT ANY WARRANTY WHATSOEVER, AND IN PARTICULAR, ANY WARRANTY OF NONINFRINGEMENT IS EXPRESSLY DISCLAIMED. ANY USE OF THIS SPECIFICATION SHALL BE MADE ENTIRELY AT THE IMPLEMENTERS OWN RISK, AND NEITHER THE  CONSORTIUM, NOR ANY OF ITS MEMBERS OR SUBMITTERS, SHALL HAVE ANY LIABILITY WHATSOEVER TO ANY IMPLEMENTER OR THIRD PARTY FOR ANY DAMAGES OF ANY NATURE WHATSOEVER,  DIRECTLY OR INDIRECTLY, ARISING FROM THE USE OF THIS API DEFINITION.
    contact: 
        name: Lisa Mattson (COO), IMS Global
        url: http://www.imsglobal.org
        email: lmattson@imsglobal.org
    license: 
        name: IMS Global
        url: https://www.imsglobal.org/license.html

#####################################################################################
#                                 Servers                                           #
#####################################################################################
servers: 
    - url: www.imsglobal.org/ims/ob/v2p1
      description: The above Server URL should be changed to the actual server location.

#####################################################################################
#                                  Tags                                             #
#####################################################################################
tags: 
    - name: OB-API
      description: |
        Open Badges Connect API

#####################################################################################
#                                   Paths                                           #
#####################################################################################
paths: 
    /assertions:
        get:
            operationId: getAssertions
            summary: The REST read request message for the getAssertions() API call.
            tags: 
                - OB-API
            description: |
                Fetch Assertions for the supplied parameters and authentication token.
            parameters: 
                - name: limit
                  in: query
                  description: |
                      Indicate how many results should be retrieved in a single page.
                  required: false
                  type: integer
                  format: int32
                  allowEmptyValue: false
                  minimum: 1
                - name: offset
                  in: query
                  description: |
                      Indicate the index of the first record to return (zero indexed).
                  required: false
                  type: integer
                  format: int32
                  allowEmptyValue: false
                  minimum: 0
                - name: since
                  in: query
                  description: |
                      Retrieve Assertions that were created or updated after the provided timestamp. Must be an ISO 8601 compatible timestamp with a time zone indicator.
                  required: false
                  type: string
                  format: date-time
                  allowEmptyValue: false
            responses: 
                "200" : 
                    description: |
                        This is the response when the request has been completed successfully.
                    schema: 
                        $ref: "#/definitions/AssertionsResponse.Type"
                "400" : 
                    description: |
                        An invalid request was made.
                    schema: 
                        $ref: "#/definitions/ErrorResponse.Type"
                "401" : 
                    description: |
                        The request was not correctly authorized.
                    schema: 
                        $ref: "#/definitions/ErrorResponse.Type"
                "404" : 
                    description: |
                        The requested resource does not exist.
                    schema: 
                        $ref: "#/definitions/ErrorResponse.Type"
                "405" : 
                    description: |
                        This method is not allowed on the endpoint.
                    schema: 
                        $ref: "#/definitions/ErrorResponse.Type"
                "500" : 
                    description: |
                        This code should be used only if there is catastrophic error.
                    schema: 
                        $ref: "#/definitions/ErrorResponse.Type"
                "default" : 
                    description: |
                        Any other response.
                    schema: 
                        $ref: "#/definitions/ErrorResponse.Type"
        post:
            operationId: postAssertion
            summary: The REST update request message for the postAssertion() API call.
            tags: 
                - OB-API
            description: |
                Create or update an Assertion.
            parameters: 
                - name: assertion
                  in: body
                  description: |
                      The Assertion to be created or updated.
                  required: true
                  schema: 
                      $ref: "#/definitions/Assertion.Type"
            responses: 
                "200" : 
                    description: |
                        The Assertion was updated successfully.
                    schema: 
                        $ref: "#/definitions/AssertionsResponse.Type"
                "201" : 
                    description: |
                        The Assertion was created successfully.
                    schema: 
                        $ref: "#/definitions/AssertionsResponse.Type"
                "400" : 
                    description: |
                        An invalid request was made.
                    schema: 
                        $ref: "#/definitions/ErrorResponse.Type"
                "401" : 
                    description: |
                        The request was not correctly authorized.
                    schema: 
                        $ref: "#/definitions/ErrorResponse.Type"
                "404" : 
                    description: |
                        The requested resource does not exist.
                    schema: 
                        $ref: "#/definitions/ErrorResponse.Type"
                "405" : 
                    description: |
                        This method is not allowed on the endpoint.
                    schema: 
                        $ref: "#/definitions/ErrorResponse.Type"
                "500" : 
                    description: |
                        This code should be used only if there is catastrophic error.
                    schema: 
                        $ref: "#/definitions/ErrorResponse.Type"
                "default" : 
                    description: |
                        Any other response.
                    schema: 
                        $ref: "#/definitions/ErrorResponse.Type"

    /profile:
        get:
            operationId: getProfile
            summary: The REST read request message for the getProfile() API call.
            tags: 
                - OB-API
            description: |
                Fetch the profile for the supplied authentication token.
            responses: 
                "200" : 
                    description: |
                        This is the response when the request has been completed successfully.
                    schema: 
                        $ref: "#/definitions/ProfilesResponse.Type"
                "400" : 
                    description: |
                        An invalid request was made.
                    schema: 
                        $ref: "#/definitions/ErrorResponse.Type"
                "401" : 
                    description: |
                        The request was not correctly authorized.
                    schema: 
                        $ref: "#/definitions/ErrorResponse.Type"
                "404" : 
                    description: |
                        The requested resource does not exist.
                    schema: 
                        $ref: "#/definitions/ErrorResponse.Type"
                "405" : 
                    description: |
                        This method is not allowed on the endpoint.
                    schema: 
                        $ref: "#/definitions/ErrorResponse.Type"
                "500" : 
                    description: |
                        This code should be used only if there is catastrophic error.
                    schema: 
                        $ref: "#/definitions/ErrorResponse.Type"
                "default" : 
                    description: |
                        Any other response.
                    schema: 
                        $ref: "#/definitions/ErrorResponse.Type"
        post:
            operationId: postProfile
            summary: The REST update request message for the postProfile() API call.
            tags: 
                - OB-API
            description: |
                Update the profile for the authenticated user.
            parameters: 
                - name: profile
                  in: body
                  description: |
                      The authenticated user's profile.
                  required: true
                  schema: 
                      $ref: "#/definitions/Profile.Type"
            responses: 
                "200" : 
                    description: |
                        This is the response when the request has been completed successfully.
                    schema: 
                        $ref: "#/definitions/ProfilesResponse.Type"
                "400" : 
                    description: |
                        An invalid request was made.
                    schema: 
                        $ref: "#/definitions/ErrorResponse.Type"
                "401" : 
                    description: |
                        The request was not correctly authorized.
                    schema: 
                        $ref: "#/definitions/ErrorResponse.Type"
                "404" : 
                    description: |
                        The requested resource does not exist.
                    schema: 
                        $ref: "#/definitions/ErrorResponse.Type"
                "405" : 
                    description: |
                        This method is not allowed on the endpoint.
                    schema: 
                        $ref: "#/definitions/ErrorResponse.Type"
                "500" : 
                    description: |
                        This code should be used only if there is catastrophic error.
                    schema: 
                        $ref: "#/definitions/ErrorResponse.Type"
                "default" : 
                    description: |
                        Any other response.
                    schema: 
                        $ref: "#/definitions/ErrorResponse.Type"

