swagger: '2.0'

#####################################################################################
#                               API Information                                     #
#####################################################################################
info: 
    version: '2.1'
    title: Open Badges OpenAPI (YAML) Definition
    description: TBD
    termsOfService: Permission is granted to all parties to use excerpts from this document as needed in producing requests for proposals. The limited permissions granted above are perpetual and will not be revoked by IMS or its successors or assigns. THIS API DEFINITION IS BEING OFFERED WITHOUT ANY WARRANTY WHATSOEVER, AND IN PARTICULAR, ANY WARRANTY OF NONINFRINGEMENT IS EXPRESSLY DISCLAIMED. ANY USE OF THIS SPECIFICATION SHALL BE MADE ENTIRELY AT THE IMPLEMENTERS OWN RISK, AND NEITHER THE  CONSORTIUM, NOR ANY OF ITS MEMBERS OR SUBMITTERS, SHALL HAVE ANY LIABILITY WHATSOEVER TO ANY IMPLEMENTER OR THIRD PARTY FOR ANY DAMAGES OF ANY NATURE WHATSOEVER,  DIRECTLY OR INDIRECTLY, ARISING FROM THE USE OF THIS API DEFINITION.
    contact: 
        name: Lisa Mattson (COO), IMS Global
        url: http://www.imsglobal.org
        email: lmattson@imsglobal.org
    license: 
        name: IMS Global
        url: https://www.imsglobal.org/license.html

#####################################################################################
#                   Host, Base Path, Schemes and Content Types                      #
#####################################################################################
host: 
basePath: 
schemes: 
    - http
    - https
consumes: 
    - application/json
produces: 
    - application/json

#####################################################################################
#                                  Tags                                             #
#####################################################################################
tags: 
    - name: OBC-Manifest
      description: |
        Open Badges Connect Service Manifest interface.

#####################################################################################
#                                 Security                                          #
#####################################################################################

#####################################################################################
#                                   Paths                                           #
#####################################################################################
paths: 
    /.well-known/badgeconnect.json:
        get:
            operationId: getManifest
            summary: The REST read request message for the getManifest() API call.
            tags: 
                - OBC-Manifest
            description: |
                Open Badges Connect Service manifest read operation.
            responses: 
                "200" : 
                    description: |
                        This is the response when the request has been completed successfully.
                    schema: 
                        $ref: "#/definitions/Manifest.Type"
                "404" : 
                    description: |
                        This is the response when the provider does not support the badge connect API.
                "421" : 
                    description: |
                        This is the response when the request was not made over secure TLS protocol.
                "default" : 
                    description: |
                        This is the response when some other error has occured.


#####################################################################################
#                               Definitions                                         #
#####################################################################################
definitions: 
    BadgeConnectAPI.Type:
        description: |
            Configuration information about a single implementation.
        type: object
        required: 
            - name
            - apiBase
            - scopesOffered
            - version
            - registrationUrl
            - authorizationUrl
            - tokenUrl
            - termsOfServiceUrl
            - privacyPolicyUrl
        properties: 
            id: 
                description: Unique IRI for the configuration. Model Primitive Datatype = AnyURI.
                type: string
                format: uri
            type: 
                description: JSON-LD type of the configuration object. Defaults to BadgeConnectAPI. Model Primitive Datatype = AnyURI.
                type: string
                format: uri
            name: 
                description: The name of the platform supporting the API. This SHOULD reflect the user-facing identity of the platform requesting authorization. Model Primitive Datatype = String.
                type: string
            image: 
                description: An image representing the platform. May be a URI to a hosted image or a Data URI. Model Primitive Datatype = AnyURI.
                type: string
                format: uri
            apiBase: 
                description: Fully qualified URL that will be concatenated with the API endpoints. It SHOULD NOT have a trailing slash '/'. E.g. apiBase + '/assertions'. Model Primitive Datatype = AnyURI.
                type: string
                format: uri
            scopesOffered: 
                description: Applies to Hosts only. An array of strings listing the scopes supported by the Host in the form of fully qualified URLs to the scope descriptors. Model Primitive Datatype = AnyURI.
                type: array
                minItems: 1
                items: 
                    type: string
                    format: uri
            version: 
                description: A string representing the implemented version. MUST be in the format of vMAJORpMINOR where MAJOR and MINOR are integers. Model Primitive Datatype = String.
                type: string
            registrationUrl: 
                description: A fully qualifed URL to the host's dynamic client registration endpoint. Model Primitive Datatype = AnyURI.
                type: string
                format: uri
            authorizationUrl: 
                description: A fully qualified URL to the host's authorization endpoint. Model Primitive Datatype = AnyURI.
                type: string
                format: uri
            tokenUrl: 
                description: A fully qualified URL to the host's token request endpoint for exchanging an authorization code for a bearer token. Model Primitive Datatype = AnyURI.
                type: string
                format: uri
            tokenRevocationUrl: 
                description: A fully qualifed URL to the host's token revocation endpoint. Model Primitive Datatype = AnyURI.
                type: string
                format: uri
            termsOfServiceUrl: 
                description: A fully qualified URL to the platform's terms of service. Other platforms SHOULD link to this resource as part of their authorization interface. Model Primitive Datatype = AnyURI.
                type: string
                format: uri
            privacyPolicyUrl: 
                description: A fully qualified URL to the platform's privacy policy. Other platforms SHOULD link to this resource as part of their authorization interface. Model Primitive Datatype = AnyURI.
                type: string
                format: uri
        additionalProperties: false
    Manifest.Type:
        description: |
            Provider configuration information. A provider may support multiple implementations.
        type: object
        required: 
            - @context
            - id
            - badgeConnectAPI
        properties: 
            @context: 
                description: The URL of the JSON-LD @context file for the manifest. Model Primitive Datatype = AnyURI.
                type: string
                format: uri
            id: 
                description: Unique IRI for the manifest. Model Primitive Datatype = AnyURI.
                type: string
                format: uri
            type: 
                description: The JSON-LD type of the manifest. Defaults to Manifest. Model Primitive Datatype = AnyURI.
                type: string
                format: uri
            badgeConnectAPI: 
                description: |
                    Set of BadgeConnectAPI configurations.
                type: array
                minItems: 1
                items: 
                    $ref: "#/definitions/BadgeConnectAPI.Type"
        additionalProperties: false
