name: Publish the JSON-LD context file

on:
  push:
    branches: 
      - develop
    paths: 
      - 'ob_v3p0/context.json'
  pull_request:
    branches: 
      - develop
    paths: 
      - 'ob_v3p0/context.json'

jobs:

  publish:
    name: Publish to GH pages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout gh-pages
        uses: actions/checkout@v2
        with:
          ref: gh-pages
      - name: Update context.json
        run: |
          git checkout develop ob_v3p0/context.json
          cp ob_v3p0/context.json docs/context.json
      - name: Commit the changes
        run: |
          git add docs/*
          git config --local user.name "GitHub Actions"
          git config --local user.email "actions@github.com"
          git commit --allow-empty -m "Automated build"
          git push origin
