name: Publish the JSON-LD context file

on:
  push:
    branches: 
      - develop
    paths: 
      - 'ob_v3p0/context.json'
  pull_request:
    branches: 
      - develop
    paths: 
      - 'ob_v3p0/context.json'

jobs:

  publish:
    name: Publish to GH pages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Copy the context file
        run: cp ob_v3p0/context.json docs/
      - name: Commit the changes
        uses: zwaldowski/git-commit-action@v1
      - name: Push the changes
        run: git push origin
