name: Build OB 3.0 Spec Preview for PUSH 

on:
  # Triggers the workflow on push or pull request events but only for the develop branch
  push:
    branches: 
      - develop
    paths: 
      - 'ob_v3p0/**'
      - '!ob_v3p0/context.json'
      - '!ob_v3p0/readme.md'
      - '!ob_v3p0/examples.html'
      - '.github/workflows/ob_v3p0_push.yml'

jobs:
  
  sideload:
    name: Sideload the ob_v3p0.lines file
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: curl -H 'X-Api-Key:${{ secrets.API_KEY }}' -F 'file=@ob_v3p0/ob_v3p0.lines' https://datamodels-staging.imsglobal.org/upload
        continue-on-error: false
  
  openapi:
    name: Generate the OpenAPI files
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: curl -H 'X-Api-Key:${{ secrets.API_KEY }}' https://datamodels-staging.imsglobal.org/openapischema/org.1edtech.ob.v3p0.model?binding=json --output openapi.json
      - run: curl -H 'X-Api-Key:${{ secrets.API_KEY }}' https://datamodels-staging.imsglobal.org/openapischema/org.1edtech.ob.v3p0.model?binding=yaml --output openapi.yaml
      - name: Upload OpenAPI files
        uses: actions/upload-artifact@v3
        with: 
          path: openapi.*
      - name: Switch to gh-pages branch
        uses: actions/checkout@v2
        with:
          ref: gh-pages
      - name: Download the OpenAPI files
        uses: actions/download-artifact@v3
        with: 
          path: docs
      - name: Commit the new/updated doc
        run: |
          git add docs/*
          git config --local user.name "GitHub Actions"
          git config --local user.email "actions@github.com"
          git commit --allow-empty -m "Automated build"
          git push origin
  
  build:
    name: Build a static version of the Respec document
    needs: sideload
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Unlock secrets
        uses: sliteteam/github-action-git-crypt-unlock@1.2.0
        env:
          GIT_CRYPT_KEY: ${{ secrets.GIT_CRYPT_KEY }}
      # This will run the respec2html tool
      - uses: w3c/spec-prod@v2
        with:
          SOURCE: "ob_v3p0/ob_v3p0.html"
          DESTINATION: "docs/ob_v3p0.html"
          TOOLCHAIN: respec
          VALIDATE_MARKUP: false
          VALIDATE_WEBIDL: false
          VALIDATE_LINKS: false
          BUILD_FAIL_ON: nothing

  publish:
    name: Publish to GH pages
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: gh-pages
      - name: Download artifact created by build job
        uses: actions/download-artifact@v2
        with: 
          name: spec-prod-result
          path: docs
      - name: Commit the new/updated doc
        run: |
          git add docs/*
          git config --local user.name "GitHub Actions"
          git config --local user.email "actions@github.com"
          git commit --allow-empty -m "Automated build"
          git push origin
