name: Build OB 3.0 Spec Preview for PR

on:
  # Triggers the workflow on push or pull request events but only for the develop branch
  pull_request:
    branches:
      - develop

jobs:

  sideload:
    name: Sideload the ob_v3p0.lines file
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: curl -H 'X-Api-Key:${{ secrets.API_KEY }}' -F 'file=@ob_v3p0/ob_v3p0.lines' https://datamodels-staging.imsglobal.org/upload
        continue-on-error: false

  build:
    name: Build a static version of the Respec document
    needs: sideload
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - source: 'ob_v3p0/ob_v3p0.html'
            destination: 'docs/ob_v3p0.html'
          - source: 'ob_v3p0/errata/ob_v3p0.html'
            destination: 'docs/ob_err_v3p0.html'
    steps:
      - uses: actions/checkout@v2
      - name: Unlock secrets
        uses: sliteteam/github-action-git-crypt-unlock@1.2.0
        env:
          GIT_CRYPT_KEY: ${{ secrets.GIT_CRYPT_KEY }}
      - uses: w3c/spec-prod@v2
        with:
          SOURCE: ${{ matrix.source }}
          DESTINATION: ${{ matrix.destination }}
          TOOLCHAIN: respec
          VALIDATE_MARKUP: false
          VALIDATE_WEBIDL: false
          VALIDATE_LINKS: false
          BUILD_FAIL_ON: nothing

  publish:
    name: Publish to GH pages
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Get branch name from PR
        uses: andrevalentin/get-branch-name-by-pr@v1
        id: pr_data
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          pr-id: ${{ github.event.number }}
      - name: Checkout the branch
        uses: actions/checkout@v2
        with:
          ref: ${{ steps.pr_data.outputs.branch }}
      - name: Download artifact created by build job
        uses: actions/download-artifact@v2
        with:
          name: spec-prod-result
          path: docs
      - name: Commit the new/updated doc
        run: |
          git pull
          git add -f docs/*
          git config --local user.name "GitHub Actions"
          git config --local user.email "actions@github.com"
          git commit --allow-empty -m "Automated build"
          git push origin
