# This is a basic workflow to help you get started with Actions

name: Build OB 3.0 Spec Preview

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the develop branch
  push:
    branches: 
      - develop
    paths: 
      - 'ob_v3p0/**'
      - '.github/workflows/*'
  pull_request:
    branches: 
      - develop

jobs:
  # This workflow contains a single job called "publish"
  build:
    name: Build a static version of the Respec document

    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
#        with:
#          ref: "gh-pages"
      - name: Unlock secrets
        uses: sliteteam/github-action-git-crypt-unlock@1.2.0
        env:
          GIT_CRYPT_KEY: ${{ secrets.GIT_CRYPT_KEY }}
      - uses: w3c/spec-prod@v2
        with:
#         GH_PAGES_BRANCH: "gh-pages"
          SOURCE: "ob_v3p0/ob_v3p0.html"
          DESTINATION: "docs/ob_v3p0.html"
          TOOLCHAIN: respec
          VALIDATE_MARKUP: false
          VALIDATE_WEBIDL: false
          VALIDATE_LINKS: false
          BUILD_FAIL_ON: nothing

  publish:
    name: Publish to GH pages
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout gh-pages
        uses: actions/checkout@v2
        with:
          ref: gh-pages
      - run: ls docs -l -R
      - name: Download artifact created by build job
        uses: actions/download-artifact@v2
        with: 
          name: spec-prod-result
          path: docs
      - run: ls docs -l -R
