name: Publish Extensions

on:
  # Triggers the workflow on push or pull request events but only for the develop branch
  push:
    branches:
      - develop
    paths:
      - 'extensions/**'
  workflow_dispatch:

jobs:
  find-lines-files:
    runs-on: ubuntu-latest
    outputs:
      files: ${{ steps.set-files.outputs.files }}
    steps:
      - uses: actions/checkout@v4
      - id: set-files
        run: |
          files=$(find extensions/ -type f -name "*.lines" | paste -sd "," -)
          echo "files=$files" >> $GITHUB_OUTPUT

  process-lines-files:
    needs: find-lines-files
    runs-on: ubuntu-latest
    strategy:
      matrix:
        file: ${{ fromJson(needs.find-lines-files.outputs.files) }}
    steps:
      - uses: actions/checkout@v4
      - name: Sideload the lines file
        run: curl -H 'X-Api-Key:${{ secrets.MPS_API_KEY }}' -F 'file=@${{ matrix.file }}' https://mps.1edtech.org/upload
        continue-on-error: false
  publish:
    name: Publish to GH pages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout develop
        uses: actions/checkout@v4
        with:
          ref: develop
      - name: Upload extensions from develop
        uses: actions/upload-artifact@v4
        with:
          name: extensions
          path: extensions
      - uses: actions/checkout@v2
        with:
          ref: gh-pages
      - name: Download artifact created by build job
        uses: actions/download-artifact@v4
        with:
          name: extensions
          path: docs/extensions
      - name: Commit the new/updated doc
        run: |
          git pull
          git add docs/extensions*
          git config --local user.name "GitHub Actions"
          git config --local user.email "actions@github.com"
          git commit --allow-empty -m "Automated build"
          git push origin
